# Generated by Django 2.0.1 on 2018-03-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=140)),
                ('category', models.CharField(max_length=140)),
                ('plate', models.CharField(max_length=140)),
                ('brand', models.CharField(max_length=140)),
                ('engine_no', models.IntegerField()),
                ('hourly_fuel_consumption', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=140)),
                ('purchase_date', models.DateField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
